*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 03.08.2018 at 15:06:04
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZVCA_INTF_INFO..................................*
FORM GET_DATA_ZVCA_INTF_INFO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTCA_INTF_INFO WHERE
(VIM_WHERETAB) .
    CLEAR ZVCA_INTF_INFO .
ZVCA_INTF_INFO-MANDT =
ZTCA_INTF_INFO-MANDT .
ZVCA_INTF_INFO-ZZINTFNAM =
ZTCA_INTF_INFO-ZZINTFNAM .
ZVCA_INTF_INFO-ZZINTFDESC =
ZTCA_INTF_INFO-ZZINTFDESC .
ZVCA_INTF_INFO-OBJECT =
ZTCA_INTF_INFO-OBJECT .
ZVCA_INTF_INFO-SUBOBJECT =
ZTCA_INTF_INFO-SUBOBJECT .
ZVCA_INTF_INFO-ZZEXTIDTYP =
ZTCA_INTF_INFO-ZZEXTIDTYP .
ZVCA_INTF_INFO-ZZSTORE_X =
ZTCA_INTF_INFO-ZZSTORE_X .
ZVCA_INTF_INFO-ZZMIDDLEWARE_X =
ZTCA_INTF_INFO-ZZMIDDLEWARE_X .
ZVCA_INTF_INFO-ZZPRIO =
ZTCA_INTF_INFO-ZZPRIO .
ZVCA_INTF_INFO-ZZSNDSYS =
ZTCA_INTF_INFO-ZZSNDSYS .
ZVCA_INTF_INFO-ZZRECSYS =
ZTCA_INTF_INFO-ZZRECSYS .
ZVCA_INTF_INFO-ZZSNDINTFTYPE =
ZTCA_INTF_INFO-ZZSNDINTFTYPE .
ZVCA_INTF_INFO-ZZRCVINTFTYPE =
ZTCA_INTF_INFO-ZZRCVINTFTYPE .
ZVCA_INTF_INFO-ZZACK_X =
ZTCA_INTF_INFO-ZZACK_X .
ZVCA_INTF_INFO-ZZEMAIL_BUSOWN =
ZTCA_INTF_INFO-ZZEMAIL_BUSOWN .
ZVCA_INTF_INFO-ZZEMAIL_IT =
ZTCA_INTF_INFO-ZZEMAIL_IT .
ZVCA_INTF_INFO-ZZEMAIL_TECH_SND =
ZTCA_INTF_INFO-ZZEMAIL_TECH_SND .
ZVCA_INTF_INFO-ZZEMAIL_TECH_RCV =
ZTCA_INTF_INFO-ZZEMAIL_TECH_RCV .
ZVCA_INTF_INFO-ZZEMAIL_BUS =
ZTCA_INTF_INFO-ZZEMAIL_BUS .
ZVCA_INTF_INFO-ZZREMARKS =
ZTCA_INTF_INFO-ZZREMARKS .
<VIM_TOTAL_STRUC> = ZVCA_INTF_INFO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVCA_INTF_INFO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVCA_INTF_INFO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVCA_INTF_INFO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTCA_INTF_INFO WHERE
  ZZINTFNAM = ZVCA_INTF_INFO-ZZINTFNAM .
    IF SY-SUBRC = 0.
    DELETE ZTCA_INTF_INFO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTCA_INTF_INFO WHERE
  ZZINTFNAM = ZVCA_INTF_INFO-ZZINTFNAM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTCA_INTF_INFO.
    ENDIF.
ZTCA_INTF_INFO-MANDT =
ZVCA_INTF_INFO-MANDT .
ZTCA_INTF_INFO-ZZINTFNAM =
ZVCA_INTF_INFO-ZZINTFNAM .
ZTCA_INTF_INFO-ZZINTFDESC =
ZVCA_INTF_INFO-ZZINTFDESC .
ZTCA_INTF_INFO-OBJECT =
ZVCA_INTF_INFO-OBJECT .
ZTCA_INTF_INFO-SUBOBJECT =
ZVCA_INTF_INFO-SUBOBJECT .
ZTCA_INTF_INFO-ZZEXTIDTYP =
ZVCA_INTF_INFO-ZZEXTIDTYP .
ZTCA_INTF_INFO-ZZSTORE_X =
ZVCA_INTF_INFO-ZZSTORE_X .
ZTCA_INTF_INFO-ZZMIDDLEWARE_X =
ZVCA_INTF_INFO-ZZMIDDLEWARE_X .
ZTCA_INTF_INFO-ZZPRIO =
ZVCA_INTF_INFO-ZZPRIO .
ZTCA_INTF_INFO-ZZSNDSYS =
ZVCA_INTF_INFO-ZZSNDSYS .
ZTCA_INTF_INFO-ZZRECSYS =
ZVCA_INTF_INFO-ZZRECSYS .
ZTCA_INTF_INFO-ZZSNDINTFTYPE =
ZVCA_INTF_INFO-ZZSNDINTFTYPE .
ZTCA_INTF_INFO-ZZRCVINTFTYPE =
ZVCA_INTF_INFO-ZZRCVINTFTYPE .
ZTCA_INTF_INFO-ZZACK_X =
ZVCA_INTF_INFO-ZZACK_X .
ZTCA_INTF_INFO-ZZEMAIL_BUSOWN =
ZVCA_INTF_INFO-ZZEMAIL_BUSOWN .
ZTCA_INTF_INFO-ZZEMAIL_IT =
ZVCA_INTF_INFO-ZZEMAIL_IT .
ZTCA_INTF_INFO-ZZEMAIL_TECH_SND =
ZVCA_INTF_INFO-ZZEMAIL_TECH_SND .
ZTCA_INTF_INFO-ZZEMAIL_TECH_RCV =
ZVCA_INTF_INFO-ZZEMAIL_TECH_RCV .
ZTCA_INTF_INFO-ZZEMAIL_BUS =
ZVCA_INTF_INFO-ZZEMAIL_BUS .
ZTCA_INTF_INFO-ZZREMARKS =
ZVCA_INTF_INFO-ZZREMARKS .
    IF SY-SUBRC = 0.
    UPDATE ZTCA_INTF_INFO .
    ELSE.
    INSERT ZTCA_INTF_INFO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVCA_INTF_INFO-UPD_FLAG,
STATUS_ZVCA_INTF_INFO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVCA_INTF_INFO.
  SELECT SINGLE * FROM ZTCA_INTF_INFO WHERE
ZZINTFNAM = ZVCA_INTF_INFO-ZZINTFNAM .
ZVCA_INTF_INFO-MANDT =
ZTCA_INTF_INFO-MANDT .
ZVCA_INTF_INFO-ZZINTFNAM =
ZTCA_INTF_INFO-ZZINTFNAM .
ZVCA_INTF_INFO-ZZINTFDESC =
ZTCA_INTF_INFO-ZZINTFDESC .
ZVCA_INTF_INFO-OBJECT =
ZTCA_INTF_INFO-OBJECT .
ZVCA_INTF_INFO-SUBOBJECT =
ZTCA_INTF_INFO-SUBOBJECT .
ZVCA_INTF_INFO-ZZEXTIDTYP =
ZTCA_INTF_INFO-ZZEXTIDTYP .
ZVCA_INTF_INFO-ZZSTORE_X =
ZTCA_INTF_INFO-ZZSTORE_X .
ZVCA_INTF_INFO-ZZMIDDLEWARE_X =
ZTCA_INTF_INFO-ZZMIDDLEWARE_X .
ZVCA_INTF_INFO-ZZPRIO =
ZTCA_INTF_INFO-ZZPRIO .
ZVCA_INTF_INFO-ZZSNDSYS =
ZTCA_INTF_INFO-ZZSNDSYS .
ZVCA_INTF_INFO-ZZRECSYS =
ZTCA_INTF_INFO-ZZRECSYS .
ZVCA_INTF_INFO-ZZSNDINTFTYPE =
ZTCA_INTF_INFO-ZZSNDINTFTYPE .
ZVCA_INTF_INFO-ZZRCVINTFTYPE =
ZTCA_INTF_INFO-ZZRCVINTFTYPE .
ZVCA_INTF_INFO-ZZACK_X =
ZTCA_INTF_INFO-ZZACK_X .
ZVCA_INTF_INFO-ZZEMAIL_BUSOWN =
ZTCA_INTF_INFO-ZZEMAIL_BUSOWN .
ZVCA_INTF_INFO-ZZEMAIL_IT =
ZTCA_INTF_INFO-ZZEMAIL_IT .
ZVCA_INTF_INFO-ZZEMAIL_TECH_SND =
ZTCA_INTF_INFO-ZZEMAIL_TECH_SND .
ZVCA_INTF_INFO-ZZEMAIL_TECH_RCV =
ZTCA_INTF_INFO-ZZEMAIL_TECH_RCV .
ZVCA_INTF_INFO-ZZEMAIL_BUS =
ZTCA_INTF_INFO-ZZEMAIL_BUS .
ZVCA_INTF_INFO-ZZREMARKS =
ZTCA_INTF_INFO-ZZREMARKS .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVCA_INTF_INFO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVCA_INTF_INFO-ZZINTFNAM TO
ZTCA_INTF_INFO-ZZINTFNAM .
MOVE ZVCA_INTF_INFO-MANDT TO
ZTCA_INTF_INFO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTCA_INTF_INFO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTCA_INTF_INFO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTCA_INTF_INFO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVCA_INTF_INFOST................................*
FORM GET_DATA_ZVCA_INTF_INFOST.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTCA_INTF_INFOST WHERE
(VIM_WHERETAB) .
    CLEAR ZVCA_INTF_INFOST .
ZVCA_INTF_INFOST-MANDT =
ZTCA_INTF_INFOST-MANDT .
ZVCA_INTF_INFOST-ZZINTFNAM =
ZTCA_INTF_INFOST-ZZINTFNAM .
ZVCA_INTF_INFOST-ZZSTORE =
ZTCA_INTF_INFOST-ZZSTORE .
    SELECT SINGLE * FROM T001W WHERE
WERKS = ZTCA_INTF_INFOST-ZZSTORE .
    IF SY-SUBRC EQ 0.
ZVCA_INTF_INFOST-NAME1 =
T001W-NAME1 .
    ENDIF.
<VIM_TOTAL_STRUC> = ZVCA_INTF_INFOST.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVCA_INTF_INFOST .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVCA_INTF_INFOST.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVCA_INTF_INFOST-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTCA_INTF_INFOST WHERE
  ZZINTFNAM = ZVCA_INTF_INFOST-ZZINTFNAM AND
  ZZSTORE = ZVCA_INTF_INFOST-ZZSTORE .
    IF SY-SUBRC = 0.
    DELETE ZTCA_INTF_INFOST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTCA_INTF_INFOST WHERE
  ZZINTFNAM = ZVCA_INTF_INFOST-ZZINTFNAM AND
  ZZSTORE = ZVCA_INTF_INFOST-ZZSTORE .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTCA_INTF_INFOST.
    ENDIF.
ZTCA_INTF_INFOST-MANDT =
ZVCA_INTF_INFOST-MANDT .
ZTCA_INTF_INFOST-ZZINTFNAM =
ZVCA_INTF_INFOST-ZZINTFNAM .
ZTCA_INTF_INFOST-ZZSTORE =
ZVCA_INTF_INFOST-ZZSTORE .
    IF SY-SUBRC = 0.
    UPDATE ZTCA_INTF_INFOST .
    ELSE.
    INSERT ZTCA_INTF_INFOST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVCA_INTF_INFOST-UPD_FLAG,
STATUS_ZVCA_INTF_INFOST-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVCA_INTF_INFOST.
  SELECT SINGLE * FROM ZTCA_INTF_INFOST WHERE
ZZINTFNAM = ZVCA_INTF_INFOST-ZZINTFNAM AND
ZZSTORE = ZVCA_INTF_INFOST-ZZSTORE .
ZVCA_INTF_INFOST-MANDT =
ZTCA_INTF_INFOST-MANDT .
ZVCA_INTF_INFOST-ZZINTFNAM =
ZTCA_INTF_INFOST-ZZINTFNAM .
ZVCA_INTF_INFOST-ZZSTORE =
ZTCA_INTF_INFOST-ZZSTORE .
    SELECT SINGLE * FROM T001W WHERE
WERKS = ZTCA_INTF_INFOST-ZZSTORE .
    IF SY-SUBRC EQ 0.
ZVCA_INTF_INFOST-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVCA_INTF_INFOST-NAME1 .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVCA_INTF_INFOST USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVCA_INTF_INFOST-ZZINTFNAM TO
ZTCA_INTF_INFOST-ZZINTFNAM .
MOVE ZVCA_INTF_INFOST-ZZSTORE TO
ZTCA_INTF_INFOST-ZZSTORE .
MOVE ZVCA_INTF_INFOST-MANDT TO
ZTCA_INTF_INFOST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTCA_INTF_INFOST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTCA_INTF_INFOST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTCA_INTF_INFOST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVCA_INTF_INFOST USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTCA_INTF_INFOST-MANDT =
ZVCA_INTF_INFOST-MANDT .
ZTCA_INTF_INFOST-ZZINTFNAM =
ZVCA_INTF_INFOST-ZZINTFNAM .
ZTCA_INTF_INFOST-ZZSTORE =
ZVCA_INTF_INFOST-ZZSTORE .
    SELECT SINGLE * FROM T001W WHERE
WERKS = ZTCA_INTF_INFOST-ZZSTORE .
    IF SY-SUBRC EQ 0.
ZVCA_INTF_INFOST-NAME1 =
T001W-NAME1 .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVCA_INTF_INFOST-NAME1 .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
